# -*- coding: utf-8 -*-
"""24-09-02-what-is-your-name-?

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOG3v-X9qOo2DC2HsU3YuR2xZbWM_o0I
"""

print("what is your name?")

#many power mode

